####################################################################################################
# Charticulator configuration file
####################################################################################################

#------------------------------------------------
# Configure extensions if any
#------------------------------------------------


#------------------------------------------------
# Allow communication with another domain. It requires for post message.
#------------------------------------------------

# CorsPolicy:
#   TargetOrigins: https://charticulator.com

# Extensions:
#   - script: extensions/extension.js
#     initialize: |
#       let extension = new MyExtensionClass(); // defined in extension.js
#       application.addExtension(extension);


#------------------------------------------------
# Configure sample datasets if any
#------------------------------------------------

# SampleDatasets:
#   - name: DatasetName
#     description: Dataset description
#     tables:
#       - name: TableName
#         type: csv/tsv
#         url: "relative/absolute url to the file"

#------------------------------------------------
# Configure the map service
#------------------------------------------------
MapService:
  ## Option 1: Use Bing Map Service
  ##   a. Obtain an API key here: https://msdn.microsoft.com/en-us/library/ff428642.aspx
  ##   b. Uncomment the following:

  # provider: Bing
  # apiKey: "TODO: put your api key here"

  ## Option 2: Use Google Map Service
  ##   a. Obtain an API key here: https://developers.google.com/maps/documentation/static-maps/
  ##   b. Uncomment the following:

  # provider: Google
  # apiKey: "TODO: put your api key here"

#------------------------------------------------
# Configure panels layout
#------------------------------------------------
  MainView:
    ColumnsPosition: left
    EditorPanelsPosition: left
    ToolbarPosition: top

#------------------------------------------------
# Configure the display of legal notices
#------------------------------------------------
LegalNotices:
  ## The privacy statement and trademark for the "New" panel
  ## Below is the statement we use in our Microsoft release.
  privacyStatementHTML: |
    <p>
      <b>A note about privacy:</b>
      We collect anonymous usage information such as the number of charts you create, the number of components in each chart, and the size of imported datasets. 
      Except these statistics, your data remains on your machine and is not shared with <a title="Microsoft" href="http://microsoft.com">Microsoft</a>.  If you have privacy concerns, Charticulator can be built from source and hosted on your own server.
      By using this service, you agree to
      <a title="Microsoft" href="http://microsoft.com">Microsoft</a>'s
      <a title="Privacy" href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy Statement</a>
      and
      <a title="Terms of Use" href="https://go.microsoft.com/fwlink/?LinkID=760869">Terms of Use</a>.
    </p>
    <p>
      <a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy & cookies</a> |
      <a href="https://go.microsoft.com/fwlink/?LinkID=760869">Terms of use</a> |
      <a href="http://go.microsoft.com/fwlink/?LinkId=506942">Trademarks</a> |
      <a href="http://choice.microsoft.com/">About our ads</a> |
      Copyright 2022 Microsoft Corporation
    </p>
